In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [ ]:
def dft_matrix(N):
    """
    Generate the normalized DFT matrix F of size (N, N).
    F_{jk} = 1/sqrt(N) * exp(-2 * pi * i * j * k / N)
    """
    # Generate the row indices (j) and column indices (k)
    j = torch.arange(N).view(-1, 1)  # shape (N, 1)
    k = torch.arange(N).view(1, -1)  # shape (1, N)

    # Compute the complex exponential part (exp(-2 * pi * i * j * k / N))
    exponent = -2j * torch.pi * j * k / N
    F = (1 / torch.sqrt(torch.tensor(N, dtype=torch.float32))) * torch.exp(exponent)

    return F

# Example usage
N = 8  # Size of the matrix
F = dft_matrix(N)

print(F)

In [ ]:
F_inv = torch.linalg.inv(F)
F_inv_conj_transpose = torch.conj(F).transpose(0, 1)
F_inv_check = torch.allclose(F_inv, F_inv_conj_transpose)
print("F_inv is equal to the conjugate transpose of F:", F_inv_check)


In [ ]:
F_inv_conj_transpose.dtype

In [ ]:
N = 8
F = dft_matrix(8).to(torch.complex64)
F_inv = torch.conj(F).transpose(0, 1)
a = torch.Tensor([1, 2, 3, 4, 4, 3, 2, 1]).to(torch.complex64)
A = torch.diag(a)
C = F @ A @ F_inv
print(C.real)



In [ ]:
C.real.dtype

In [2]:
abc = torch.randn(1, 100)
output = F.avg_pool1d(abc, kernel_size=20, padding="same")
output.shape

TypeError: avg_pool1d(): argument 'padding' must be tuple of ints, not str

In [5]:
W = torch.randint(1, 6, (1,6))
print(W)

tensor([[5, 3, 4, 1, 2, 2]])


In [7]:
torch.flip(W, dims=[1])

tensor([[2, 2, 1, 4, 3, 5]])

In [ ]:
torch.eye(8).

tensor([[1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1.]])